# Generated by Django 6.0.5 on 2026-05-22 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorAccessRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('payment_status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('fee_usdt', models.DecimalField(decimal_places=8, default=5, max_digits=20)),
                ('ref_slug', models.CharField(db_index=True, help_text='Desired short code, e.g. ALEE24', max_length=32)),
                ('payment_txid', models.CharField(blank=True, max_length=255, null=True)),
                ('payment_wallet', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor_access_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sponsor access request',
                'verbose_name_plural': 'Sponsor access requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='sponsor_req_user_st_idx')],
            },
        ),
    ]
