# Generated by Django 6.0.5 on 2026-05-26 14:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sponsor', '0002_sponsor_access'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorRewardClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_investment_usdt', models.DecimalField(decimal_places=8, max_digits=20)),
                ('reward_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('gross_reward_usdt', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_usdt', models.DecimalField(decimal_places=8, max_digits=20)),
                ('amount_coins', models.DecimalField(decimal_places=8, max_digits=20)),
                ('coin_rate_at_claim', models.DecimalField(decimal_places=8, max_digits=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='approved', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multi_level_reward_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='spnreward_user_ct_idx')],
            },
        ),
    ]
