# Generated by Django 6.0.5 on 2026-05-21 10:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0005_profitclaim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='profitclaim',
            name='amount_coins',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='profitclaim',
            name='amount_usdt',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='profitclaim',
            name='base_usdt_snapshot',
            field=models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='profitclaim',
            name='profit_cycle_hours',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profitclaim',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='profitclaim',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profit_claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='profit_cycle_hours',
            field=models.IntegerField(blank=True, default=72, help_text='Hours after coin assignment before each profit reward cycle', null=True),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='profit_enabled',
            field=models.BooleanField(blank=True, default=False, help_text='Enable profit display and reward cycle for users'),
        ),
        migrations.AlterField(
            model_name='systemsettings',
            name='profit_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Profit percentage applied to assigned purchase USDT, e.g. 10 = 10%', max_digits=5, null=True),
        ),
    ]
