# Generated by Django 6.0.5 on 2026-05-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0006_profit_fields_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sponsor_access_fee_usdt',
            field=models.DecimalField(decimal_places=8, default=5, help_text='One-time USDT fee for sponsor link access', max_digits=20),
        ),
    ]
