# Generated by Django 6.0.5 on 2026-05-26 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0007_sponsor_access'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemsettings',
            name='sponsor_reward_threshold_usdt',
            field=models.DecimalField(decimal_places=8, default=1000, help_text='Minimum total downline investment (USDT) required to activate the multi-level sponsor reward claim button.', max_digits=20),
        ),
    ]
