# Generated by Django 6.0.5 on 2026-05-22 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_hierarchy_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sponsor_access_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected')], db_index=True, default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsor_activated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsor_payment_status',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('pending', 'Pending'), ('paid', 'Paid')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='sponsor_ref_slug',
            field=models.CharField(blank=True, db_index=True, help_text='Short public ref for s24tx.com/ref/SLUG', max_length=32, null=True, unique=True),
        ),
    ]
