from django.urls import path
from . import views

urlpatterns = [
    path('admin/users', views.admin_list_users, name='admin-users'),
    path('admin/users/<int:pk>', views.admin_update_user, name='admin-update-user'),
    path('admin/users/<int:pk>/detail', views.admin_user_detail, name='admin-user-detail'),
    path('admin/purchases', views.admin_list_purchases, name='admin-purchases'),
    path('admin/purchases/<int:pk>/approve', views.admin_approve_purchase, name='admin-approve-purchase'),
    path('admin/purchases/<int:pk>/reject', views.admin_reject_purchase, name='admin-reject-purchase'),
    path('admin/purchases/<int:pk>/assign-coins', views.admin_assign_purchase_coins, name='admin-assign-purchase-coins'),
    path('admin/purchases/<int:pk>/revert-rejection', views.admin_revert_rejection, name='admin-revert-rejection'),
    path('admin/purchases/<int:pk>/documents', views.get_rejection_documents, name='admin-get-rejection-documents'),
    path('purchases/<int:purchase_id>/upload-rejection-document', views.upload_rejection_document, name='upload-rejection-document'),
    path('admin/withdrawals', views.admin_list_withdrawals, name='admin-withdrawals'),
    path('admin/withdrawals/<int:pk>/approve', views.admin_approve_withdrawal, name='admin-approve-withdrawal'),
    path('admin/withdrawals/<int:pk>/reject', views.admin_reject_withdrawal, name='admin-reject-withdrawal'),
    path('admin/claims', views.admin_list_claims, name='admin-claims'),
    path('admin/claims/<int:pk>/approve', views.admin_approve_claim, name='admin-approve-claim'),
    path('admin/claims/<int:pk>/reject', views.admin_reject_claim, name='admin-reject-claim'),
    path('admin/sponsor-access', views.admin_list_sponsor_access_requests, name='admin-sponsor-access'),
    path('admin/sponsor-access/<int:pk>/approve', views.admin_approve_sponsor_access, name='admin-approve-sponsor-access'),
    path('admin/sponsor-access/<int:pk>/reject', views.admin_reject_sponsor_access, name='admin-reject-sponsor-access'),
    path('admin/settings', views.admin_settings, name='admin-settings'),
    path('admin/sponsor', views.admin_sponsor_list, name='admin-sponsor'),
    path('admin/sponsor/tree/<int:pk>', views.admin_sponsor_tree, name='admin-sponsor-tree'),
    path('admin/sponsor/tree-root', views.admin_sponsor_tree_root, name='admin-sponsor-tree-root'),
    path('admin/stats', views.admin_stats, name='admin-stats'),
    path('admin/users/<int:pk>/delete', views.admin_delete_user, name='admin-delete-user'),
    path('admin/purchases/<int:pk>/delete', views.admin_delete_purchase, name='admin-delete-purchase'),
]
