# Generated by Django 6.0.5 on 2026-05-21 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0003_purchase_rejection_date_purchase_rejection_notes_and_more'),
        ('withdrawals', '0002_withdrawal_completed_at_withdrawal_payment_stage_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Stage 1'), (2, 'Stage 2'), (3, 'Stage 3')], null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('amount_coins', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('amount_usdt_snapshot', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('coin_rate_snapshot', models.DecimalField(blank=True, decimal_places=8, max_digits=20, null=True)),
                ('wallet_address', models.CharField(blank=True, max_length=255, null=True)),
                ('manual_tx_hash', models.CharField(blank=True, max_length=255, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('purchase', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='claims', to='purchases.purchase')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='purchase_claims', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase claim',
                'verbose_name_plural': 'Purchase claims',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['purchase', 'stage'], name='claim_purchase_stage_idx'), models.Index(fields=['user', 'status'], name='claim_user_status_idx')],
            },
        ),
    ]
